# This is a basic workflow to help you get started with Actions

name: Deployment to CPanel

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "deployment-to-cpanel" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  FTP-Deploy-Action:
    # The type of runner that the job will run on
		name: FTP-Deploy-Action
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
				with: 
					fetch-depth: 2
			- name: FTP-Deploy-Action
				uses: SamKirkland/FTP-Deploy-Action@3.1.1
				with:
					ftp-server: ${{ secrets.FTP_SERVER }}
					ftp-username: ${{ secrets.FTP_USERNAME }}
					ftp-password: ${{ secrets.FTP_PASSWORD }}
